---
format:
  html:
    code-links:
      - text: NetCDF Visualization Demo
        icon: file-code
        href: https://github.com/sci-visus/NSDF-WIRED/blob/main/communication/UBC%20Smoke%20Forecast%20Data%20Curation/data_notebooks/data_source/netcdf_demo.ipynb
---

# The Data Source {#sec-data-source}
It is important to understand exactly what data is available and how to obtain that data.

We encourage you to explore the dataset on [UBC's website](https://firesmoke.ca/forecasts/) to further understand the dataset's use and development by UBC.

Here we establish:

- What systems are available to obtain the smoke forecast data from UBC?
- What are in the files that UBC provides?
- What metadata is associated with the files we obtain, both from within the file and about the files as a whole?

This information **was not** determined the first time we explored this dataset. 

As seen in the later chapters, we operated under misinformed assumptions and encountered issues only resolvable by operating on the data "blindly". The purpose of this chapter is to establish the final set of information we learned about our data source after extensive exploration and manipulation.

## Overview

The Weather Forecast Research Team at the University of British Columbia (UBC) generates a short term dataset of PM2.5 smoke particulate presence in North America. This is done using their [The BlueSky Western Canada Wildfire Smoke Forecasting System](https://firesmoke.ca/resources/bsc-2014-description.pdf). Over the past 3 years, each day four times a day, UBC creates 2-day forecasts of PM2.5 smoke particulate on the ground for Canada and the continental United States. Each such forecast is downloadable as a NetCDF file or KMZ file. UBC provides access to these predictions for free on a daily basis at their website [firesmoke.ca](https://firesmoke.ca/).

## UBC Smoke Forecast Files Access
<!-- TODO CREDIT UBC -->
### Available Forecasts
All forecast files are uniquely identifiable with a forecast ID based on when their meteorology forecast is initiated, a smoke forecast initialization time, and by date. The time ranges of available files by forecast ID is shown in @tbl-time. Please note, there are occassional **failed forecasts or otherwise unavailable files** within the date ranges specified @tbl-time, see @sec-collection-info for further details.

| Forecast ID   | Meteorology Forecast Initialization (UTC) | Smoke Forecast Initialization (UTC) | Start Date   | End Date     |
|---------------|---------------------------------|----------------------------------|--------------|--------------|
| BSC00CA12-01  | 00Z                             | 08Z                              | March 4, 2021 | Present Day  |
| BSC06CA12-01  | 06Z                             | 14Z                              | March 4, 2021 | Present Day  |
| BSC12CA12-01  | 12Z                             | 20Z                              | March 3, 2021 | Present Day  |
| BSC18CA12-01  | 18Z                             | 02Z                              | March 4, 2021 | Present Day  |
: Dates for which all forecast ID datasets are publicly available. All times are in UTC and the grid size is 12 km. {#tbl-time}

<!-- TODO what do grid sizes mean, i.e. Meteorology: 00 UTC, nested 12 km + 36 km grids Smoke: 08 UTC -->

The smoke forecasts are updated daily, including the present day, so there is no fixed end date. Therefore, the latest data must be downloaded on a regular basis. We have not implemented this process yet, so the latest forecast files we use are up to June 27, 2024.

There is no official source stating the earliest available date for each forecast. So, knowing the project began in 2021, we inferenced that the earliest available date would be in 2021. Via trial and error we found the earliest available dates.

### Download Instructions {#sec-download-instructions}
To download the 2-day forecast for the forecast initialization date of one's choice, one follows the instructions below. The downloaded file can be a NetCDF or KMZ file.

Go to the URL:
`https://firesmoke.ca/forecasts/{Forecast ID}/{YYYYMMDD}{InitTime}/{File Type}`

Where:

- `YYYYMMDD` is the date of choice. 
-  `ForecastID` and `InitTime` are the chosen values as described in @tbl-access.
-  `File Type` is either `dispersion.nc` or `dispersion.kmz` for either the NetCDF file or KMZ file, respectively.

| Forecast ID   | Smoke Forecast Initialization (UTC) |
|---------------|-------------------------------------|
| `BSC00CA12-01`  | `08`                                 |
| `BSC06CA12-01`  | `14`                                 |
| `BSC12CA12-01`  | `20`                                 |
| `BSC18CA12-01`  | `02`                                 |
: UBC Smoke Forecast Data Download Parameters. {#tbl-access}

#### Download Example
Let's try downloading the forecast for January 1, 2024 where the weather forecast is initiated at 00:00:00 UTC and the smoke forecast is initialized at 08:00:00 UTC by navigating to the corresponding URL.

```{python}
forecast_id = "BSC00CA12-01"
yyyymmdd = "20210304"
init_time = "08"

url = (
    f"https://firesmoke.ca/forecasts/{forecast_id}/{yyyymmdd}{init_time}/dispersion.nc"
)

print(f"Navigate to this URL in your browser: {url}")
```

## The NetCDF File
Next, let's look at what is within the NetCDF file located at the URL in our previous example.

### File Preview
<!-- **TODO, MOVE TO ANOTHER SPOT**: To view and manipulate NetCDF files, we have selected the `xarray` Python library and created a [custom built backend](https://github.com/sci-visus/openvisuspy/blob/a2570ab485802375c075b6dbc0e3c79ebca02d02/src/openvisuspy/xarray_backend.py#L2) that connects `xarray` to the `OpenVisus` framework.

**TODO**
The file downloaded at the specified URL download the 2-day forecast for [DATE] and [TIME] one could download the following files.
[GET 2 DAY FORECAST DESCRIPTION FROM scribbles.ipynb]. -->

We load `dispersion.nc` using `xarray`, which provides a preview of the file.

```{python}
# | eval: true
import xarray as xr

ds = xr.open_dataset("data_notebooks/data_source/dispersion.nc")
ds
```

### File Attributes

`dispersion.nc` contains the following attributes. Note that for all files across forecast IDs, they have the same dimension and variable names:

#### Dimensions:
The dimensions described in @tbl-dims determine on which indicies we may index our variables.

| Dimension  | Size | Description                                                                                       |
|------------|------|---------------------------------------------------------------------------------------------------|
| TSTEP      | 51   | This dimension represents the number of time steps in the file. Each file has 51 hours represented.                                   |
| VAR        | 1    | This dimension is a placeholder for the variables in the file.     |
| DATE-TIME  | 2    | This dimension stores the date and time information for each time step.                           |
| LAY        | 1    | This dimension represents the number of layers in the file, which is 1 in this case.              |
| ROW        | 381  | This dimension represents the number of rows in the spatial grid.                                 |
| COL        | 1041 | This dimension represents the number of columns in the spatial grid.                              |
: Description of Dimensions for Indexing Data in NetCDF Files {#tbl-dims}

#### Variables:
The variables described in @tbl-vars contain the data in question that we would like to extract.

| Variable | Dimensions            | Data Type | Description                                                                            |
|----------|-----------------------|-----------|----------------------------------------------------------------------------------------|
| TFLAG    | TSTEP, VAR, DATE-TIME | int32     | This variable stores the date and time of each time step.                               |
| PM25     | TSTEP, LAY, ROW, COL | float32   | This variable contains the concentration of particulate matter (PM2.5) for each time step, layer, row, and column in the spatial grid. |
: Description of Variables in NetCDF Files {#tbl-vars}

#### Attributes
Of the 33 available attributes we use the ones shown in @tbl-attrs:
<!-- TODO NEED TO CONFIRM IF THIS IS RIGHT -->

| Attribute | Value               | Description                                                                                              |
|-----------|---------------------|----------------------------------------------------------------------------------------------------------|
| CDATE     | 2021063             | The creation date of the dataset, in YYYYDDD format.                                        |
| CTIME     | 101914              | The creation time of the dataset, in HHMMSS format.                                        |
| WDATE     | 2021063             | The date for which the weather forecast is initiated, in YYYYDDD format.                       |
| WTIME     | 101914              | The time for which the weather forecast is initiated, in HHMMSS format.                       |
| SDATE     | 2021063             | The date for which the smoke forecast is initiated,in YYYYDDD format.                            |
| STIME     | 90000               | The time for which the weather forecast is initiated, in HHMMSS format.                            |
| NCOLS     | 1041                | The number of columns in the spatial grid.                                                               |
| NROWS     | 381                 | The number of rows in the spatial grid.                                                                  |
| XORIG     | -156.0              | The origin (starting point) of the grid in the x-direction.                                              |
| YORIG     | 32.0                | The origin (starting point) of the grid in the y-direction.                                              |
| XCELL     | 0.10000000149011612 | The cell size in the x-direction.|
| YCELL     | 0.10000000149011612 | The cell size in the y-direction.|
: Description of Attributes in `dispersion.nc` {#tbl-attrs}

Let's look closer at what exactly is within one NetCDF file in the following demo.

### NetCDF Visualization Demo {#sec-netcdf-demo}
{{< embed data_notebooks/data_source/netcdf_demo.ipynb echo=true >}}

Now that we understand how to load the data and metadata from the file and process it for visualization, let's establish the data and metadata available to us across *all* NetCDF files.

## Information Across all NetCDF Files {#sec-collection-info}
Knowing what is within one NetCDF file as well as the date range for which we can download them, let's establish the metadata associated with the NetCDF files as a *collection*.

### Disk Size
For the time ranges we cover, @tbl-sizes shows how large the set of files per forecast ID are.

| Forecast ID    | Date Range                          | Size  | File Count |
|----------------|-------------------------------------|-------|------------|
| BSC00CA12-01   | March 4, 2021 - June 27, 2024          | 84G   | 1077       |
| BSC06CA12-01   | March 4, 2021 - June 27, 2024          | 78G   | 1022       |
| BSC12CA12-01   | March 3, 2021 - June 27, 2024          | 79G   | 1022       |
| BSC18CA12-01   | March 4, 2021 - June 27, 2024          | 79G   | 1023       |
| **Total**      |                                     | **320G** | **4144**   |
: File Sizes and Counts for Each Forecast ID within the Specified Date Range {#tbl-sizes}

### Temporal Data Availability {#sec-temporal-visual}
{{< embed data_notebooks/data_source/netcdf_collection_info.ipynb echo=true >}}

Now that we know what exactly is within a NetCDF file and across all the NetCDF files, we will continue to describe our data curation process. Next we describe how we load all of the data available from UBC onto our machine.

# References
firesmoke.ca website
https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html